version: 2
formats: all

sphinx:
  configuration: docs/conf.py
  
python:
    version: 3
    install:
        - requirements: source/requirements.txt
        - method: pip
          path: .

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
